# Place all the compile methods here
python:
	python2 main.py
java:
	echo "I don't will compile java on this machine :)"
c: gcc main.c -o main.o
	./main.o
c-for-order: gcc main-for-order.c -o main-for-order.o
	./main-for-order.o
